/**
 * This component is used to display a QRCode image generated by CustomQRCode component.
 * That way, we don't bother with server component and client componen at runtime.
 */

interface CustomQRCodeProps {
  payload: string;
  src: string;
}

export default function CustomQRCodeImg({ src, payload }: CustomQRCodeProps) {
  return (
    <div className="flex flex-col items-center">
      <div className="w-64 h-64 rounded-xl overflow-hidden bg-white p-4 shadow-md hover:shadow-lg transition-shadow duration-300">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={src}
          alt={`QR Code linking to ${payload}`}
          className="w-full h-full"
        />
      </div>
      <div className="mt-4 text-center">
        <a
          href={payload}
          rel="noopener noreferrer"
          className="text-xs text-[#900000] hover:underline"
        >
          {payload.replace(/^https?:\/\//, "")}
        </a>
      </div>
    </div>
  );
}
